### PR TITLE
Allow disabling Twig extension from config

### PR DESCRIPTION
**Pull request by artursvonda**
Addresses nibsirahsieu/SalvaJshrinkBundle#6

### CODE REVIEW

**Comment by EmanueleMinotto** [comment]
Use the configuration method `canBeDisabled()`: http://symfony.com/doc/current/components/config/definition.html#optional-sections

**Comment by artursvonda** [comment]
I added filter for filter options since "enabled" was messing with it and caused no output.

**Comment by EmanueleMinotto** [comment]
Merged, thank you :)

**Comment by nibsirahsieu** [comment]
:+1:

**Pull request merged**
